### PR TITLE
added new translations by Lex

### PR DESCRIPTION
**Pull request by leokim-l**

### CODE REVIEW

**Review by matentzn — CHANGES_REQUESTED** [review]
Error: leading Whitespace Check
 * count: 457
 * error_code: E2

Error: trailing Whitespace Check
 * count: 882
 * error_code: E3

Example:

```
en	nl	Hib vaccine (HP:0410305	rdfs:label	 Partial absence of specific antibody response to Haemophilus influenzae type b 	Gedeeltelijke afwezigheid van specifieke antilichaamrespons op Haemophilus influenzae type b 	OFFICIAL	orcid:0000-0002-5648-2155	MD, Geneticist	2024-11-26
```

- [ ] Use strip() or trim() functions to ensure that no leading or trailing whitespace exist in any cell.
- [ ] somehow the last line in the spreadsheet got totally broken.

**Comment by leokim-l** [comment]
Not sure what you mean with the second point, for the first I need to import this in python, which currently I don't (it goes from google directly to babelon format), no problem but I need a few minutes to do it, which I will have tomorrow.

**Comment by matentzn** [comment]
> not sure what you mean with the second point

```
en	nl	Hib vaccine (HP:0410305	rdfs:label	 Partial absence of specific antibody response to Haemophilus influenzae type b 	Gedeeltelijke afwezigheid van specifieke antilichaamrespons op Haemophilus influenzae type b 	OFFICIAL	orcid:0000-0002-5648-2155	MD, Geneticist	2024-11-26
```

This is not a legal row.. Where is the HP id?

**Review by matentzn — APPROVED** [review]
I will process it for now, but not that we have a schema specified for translator expertise: https://github.com/monarch-initiative/babelon/blob/ee210876516f54ca62ed8d33bbe175ddc5060375/src/babelon/schema/babelon.yaml#L19

Maybe do this in a future processing step!

**Comment by leokim-l** [comment]
I had no idea, sorry! Can we discuss adding more categories? I have a feeling a bioinformatician or a geneticist (if translating some term which is slightly beyond their field expertise) may neither fit in DOMAIN_EXPERT nor in LAYPERSON. We could have an intermediate category which is somewhat in between...?

**Comment by matentzn** [comment]
Of course! Any suggestion? Shall we just add those domain specific categories? I don't mind so much. Better of course would be something like "technical specialist", "domain informatician" (if that existed) 

Md imo is clearly domain expert?

**Comment by leokim-l** [comment]
Well, I can think of 2 things. 1) no constraint, just let people write what they prefer (maybe some constraint like using latin characters and maybe commas, dashes and dots) and 2) add "technical specialist" for anyone who is not a layperson but also not a domain expert.

**Comment by matentzn** [comment]
for the unconstrained case i would prefer using an open ended field like comment. we want to be able to make statistics across expert types, and an pure string field is too much work to clean for generating stats IMO. 

Technical specialist it is! Feel free to add to the babelon schema in PR, I will make a new release and you can add it here

**Comment by matentzn** [comment]
@leokim-l I changed the formatting a bit so its easier reviewing this in the future. Can you check out how the file looks like when you get a chance?

**Comment by leokim-l** [comment]
Unfortunately something went wrong here, I see translations in the google doc that are not in here...

**Pull request merged**
