### PR TITLE
Nyangumarta translation

### PR DESCRIPTION
**Pull request by tudorgroza**
Contributors: Yarlalu Thomas, Gareth Baynam (ORCID ID: 0000-0003-4920-9553)
Description of the translation: Translation was performed by the Nyangumarta Lyfe Languages champion Yarlalu Thomas in consultation with and the approval of Aboriginal Community Elders. The Lyfe Languages project is aimed at breaking down these barriers to communication by translating medical resources and terminology into the languages spoken by Indigenous communities. The translation was used to prepare and publish health and educational materials initially for rare diseases, then COVID-19 and subsequently extending to all health domains.

### CODE REVIEW

**Comment by pnrobinson** [comment]
This looks great!
I was looking through some of the translations and most of the time the word "Milpiny" seems to be used for "Nail" in English, but there is one translation were it is spelled "Mipiny" (no "l"). Unless this is an irregular form, it might need to be corrected!

**Review by matentzn — APPROVED** [review]
I made a technical review and loaded it into HPO international, all works fine.

**Comment by tudorgroza** [comment]
> This looks great! I was looking through some of the translations and most of the time the word "Milpiny" seems to be used for "Nail" in English, but there is one translation were it is spelled "Mipiny" (no "l"). Unless this is an irregular form, it might need to be corrected!

@pnrobinson - I'll go back to the team and request clarifications.

**Comment by tudorgroza** [comment]
@pnrobinson @matentzn - typo fixed!

**Review by matentzn — APPROVED** [review]

**Pull request merged**
