### PR TITLE
Added the first translations to Brazilian Portuguese

### PR DESCRIPTION
**Pull request by dilzacampos**
Submitter: Dilza Campos
I reviewed 104 translations from Joao's spreadsheet and transformed it into Babelon format.

### CODE REVIEW

**Review by matentzn — CHANGES_REQUESTED** [review]
Not a valid TSV - seems you used pandas without index=False?

**Comment by dilzacampos** [comment]
Yes, you are totally right. I don't know how to save tsv on the mac book and therefore I used pandas to save the tsv files. Now I added the option Index=False. Please check if it is correct now.

**Review by matentzn — CHANGES_REQUESTED** [review]
This looks great! Add one more column with the name `translator` and as values in the cells, your orcid, e.g. `orcid:0000-0002-7356-1779`

**Review by matentzn — APPROVED** [review]
Thanks @dilzacampos looks great!

**Pull request merged**
